version: "3.8"

services:
    django:
      build:
        dockerfile: ./backend/Dockerfile
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./backend:/backend
      ports:
        - "8000:8000"

    mongo:
      container_name: mongo
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: idioDB
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
      volumes:
        - ./db-data/mongo/:/data/db