# Generated by Django 4.1.1 on 2022-10-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitlesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.CharField(max_length=8)),
                ('original', models.CharField(blank=True, max_length=128, null=True)),
                ('translation', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EduVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('main_thought', models.CharField(blank=True, max_length=64, null=True)),
                ('source_type', models.CharField(choices=[('FILM', 'film'), ('TV-SERIES', 'TV-series'), ('MUSIC_CLIP', 'music clip'), ('OTHER', 'other')], default='OTHER', max_length=32)),
                ('source_info', models.CharField(blank=True, max_length=32, null=True)),
                ('subtitles_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idio_main.subtitlesinfo')),
            ],
        ),
    ]
