# Generated by Django 4.1.1 on 2022-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('video_file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
