# Generated by Django 3.2 on 2023-01-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('main_thought', models.CharField(blank=True, max_length=64, null=True)),
                ('main_thought_false_1', models.CharField(blank=True, max_length=64, null=True)),
                ('main_thought_false_2', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EduVideosLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_video_learned', to='idio_main.eduvideo')),
            ],
        ),
        migrations.CreateModel(
            name='EduVideosSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_video_skipped', to='idio_main.eduvideo')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSourceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name_en', models.CharField(default='/', max_length=64)),
                ('source_name_cs', models.CharField(default='/', max_length=64)),
                ('source_season_episode', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSourcesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_source_type', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubtitlesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=8)),
                ('original', models.CharField(blank=True, max_length=128, null=True)),
                ('translation', models.CharField(blank=True, max_length=128, null=True)),
                ('edu_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idio_main.eduvideo')),
            ],
        ),
        migrations.CreateModel(
            name='IdioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_value', models.CharField(max_length=13)),
                ('edu_videos_learned', models.ManyToManyField(related_name='edu_videos_learned', through='idio_main.EduVideosLearn', to='idio_main.EduVideo')),
                ('edu_videos_skipped', models.ManyToManyField(related_name='edu_videos_skipped', through='idio_main.EduVideosSkip', to='idio_main.EduVideo')),
            ],
        ),
        migrations.AddField(
            model_name='eduvideosskip',
            name='idio_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idio_user_skipped', to='idio_main.idiouser'),
        ),
        migrations.AddField(
            model_name='eduvideoslearn',
            name='idio_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idio_user_learned', to='idio_main.idiouser'),
        ),
        migrations.AddField(
            model_name='eduvideo',
            name='source_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idio_main.videosourcename'),
        ),
        migrations.AddField(
            model_name='eduvideo',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idio_main.videosourcestype'),
        ),
    ]
