# Generated by Django 3.2 on 2023-01-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idio_main', '0002_create_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiouser',
            name='last_edu_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idio_main.eduvideo'),
        ),
    ]
