# Generated by Django 3.2 on 2023-03-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idio_main', '0004_auto_20230103_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiouser',
            name='check_test',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='idiouser',
            name='learned_edu_video_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learned_edu_video_1', to='idio_main.eduvideo'),
        ),
        migrations.AddField(
            model_name='idiouser',
            name='learned_edu_video_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learned_edu_video_2', to='idio_main.eduvideo'),
        ),
        migrations.AddField(
            model_name='idiouser',
            name='learned_edu_video_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learned_edu_video_3', to='idio_main.eduvideo'),
        ),
    ]
