# Generated by Django 3.2 on 2023-03-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idio_main', '0005_auto_20230303_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiouser',
            name='check_test',
            field=models.CharField(default='1', max_length=8),
        ),
    ]
